-- Migração: tabela de vistorias/relatórios da equipe de Elétrica (aba "Elétrica"
-- do módulo Contratos / gecope_mapa_obras.html, Fase 1).
--
-- Contexto: a equipe de elétrica vistoria a parte elétrica das obras e produz
-- relatórios (PDF/DOCX). Os arquivos ficam hospedados no Google Drive (conta
-- dedicada do setor, fora do Supabase Storage, por custo/espaço) — esta tabela
-- guarda só os METADADOS de cada vistoria + o link para o arquivo no Drive.
--
-- O upload em si NÃO passa por uma Edge Function com service role: a Edge
-- Function eletrica-drive-token só autentica o usuário e devolve um access
-- token do Google de curta duração + o id da pasta da obra (Edge Functions do
-- Supabase têm um limite de payload não documentado, ~10MB, perto demais da
-- média de 5-10MB dos relatórios). O navegador faz o upload DIRETO para a API
-- do Drive com esse token, e SÓ ENTÃO insere a linha aqui usando o client
-- normal do Supabase (anon key da sessão do usuário) — é a policy de INSERT
-- abaixo, não uma service role, que autoriza essa escrita.
--
-- id_obra: aponta para contratos_edificacao (uma linha = uma obra; um contrato
-- pode ter N obras). Sem FK física — mesma convenção já usada no projeto para
-- aditivos_contrato/ficha_contrato, que também não têm FK para contratos_edificacao.
-- A Edge Function eletrica-drive-token valida que a obra existe antes de
-- devolver o token, mas o INSERT final em si (feito pelo navegador) não
-- revalida isso no banco.
--
-- Limitação aceita: a policy de INSERT não valida que drive_file_id corresponde
-- a um arquivo real no Drive — um usuário `eletrica` autenticado poderia, em
-- tese, inserir uma linha via REST direto sem nunca ter chamado a Edge
-- Function nem feito upload nenhum. Mesmo risco já aceito em outras tabelas do
-- projeto (composicoes_biblioteca); equipe pequena e de confiança, não vale a
-- complexidade de fechar isso agora.
--
-- Uso: rode este arquivo inteiro no SQL Editor do Supabase (Dashboard > SQL Editor).
--
-- Pré-checagem recomendada (rodar antes, separado, não faz parte da migração):
--   select proname from pg_proc where proname in ('meu_papel','contratos_edificacao_pode_ler');
-- Deve retornar as 2 linhas — confirma que as funções compartilhadas usadas
-- abaixo já existem em produção antes de rodar este script.

begin;

-- ── TABELA ──────────────────────────────────────────────────────────────────
create table if not exists eletrica_vistorias (
  id                    bigint generated by default as identity primary key,
  id_obra               integer not null,         -- contratos_edificacao.id_obra (mesmo tipo, ver docs/assistente/schema_dicionario.md), sem FK física (ver nota acima)
  data_vistoria         date not null,
  responsavel_nome      text not null,
  observacao            text,
  arquivo_nome_original text not null,
  arquivo_mime          text not null,
  arquivo_tamanho_bytes bigint not null,
  drive_file_id         text not null,            -- id do arquivo no Google Drive
  drive_folder_id       text not null,            -- pasta da obra no Drive (cache, evita nova busca a cada upload)
  drive_web_view_link   text,                     -- link "abrir no Drive" pronto para uso no front
  criado_por_email      text not null,            -- e-mail do usuário autenticado que enviou o relatório
  criado_em             timestamptz not null default now(),
  atualizado_em         timestamptz,
  excluido_em           timestamptz               -- soft delete (NULL = ativo); nunca DELETE físico
);

create index if not exists idx_eletrica_vistorias_obra
  on eletrica_vistorias (id_obra) where excluido_em is null;

create index if not exists idx_eletrica_vistorias_obra_data
  on eletrica_vistorias (id_obra, data_vistoria desc);

-- ── RBAC: perfil "eletrica" ganha leitura do módulo Contratos ────────────────
-- contratos_edificacao_pode_ler() é o gate real de leitura de todo o módulo
-- (contratos_edificacao, comissao_fiscalizacao, aditivos_contrato, ficha_contrato,
-- medicoes — ver sql/fechar_acesso_publico_contratos.sql). A equipe elétrica
-- precisa disso para ver a obra que está vistoriando. Não tocamos
-- tem_papel_valido() (governa Processos/Composições/Orçamentos, módulos alheios
-- a esta feature).
create or replace function public.contratos_edificacao_pode_ler()
 returns boolean
 language sql
 stable security definer
 set search_path to ''
as $function$
  select exists (select 1 from public.app_users u
    where lower(u.email) = lower(auth.jwt() ->> 'email')
      and u.role in ('admin','gerente','fiscal','externo','eletrica'));
$function$;

-- ── RLS ───────────────────────────────────────────────────────────────────
alter table eletrica_vistorias enable row level security;

-- leitura: mesmo público de leitura do resto do módulo Contratos
-- wrapper (select ...) por performance: evita reavaliar a função STABLE por
-- linha (mesmo padrão aplicado 2 dias antes desta migração em
-- sql/fix_rls_cache_funcoes_auxiliares.sql para as outras tabelas do módulo)
drop policy if exists "eletrica_vistorias_select" on eletrica_vistorias;
create policy "eletrica_vistorias_select"
  on eletrica_vistorias for select
  to authenticated
  using ((select public.contratos_edificacao_pode_ler()));

-- insert/update: só eletrica/admin (usa a função compartilhada public.meu_papel(),
-- já usada em sql/rls_processos_composicoes_orcamentos.sql). Sem checagem de
-- autoria (qualquer eletrica/admin pode editar/soft-deletar vistoria de outro
-- colega) — intencional para uma equipe pequena, mesmo espírito do restante do
-- módulo; revisar se a equipe crescer.
drop policy if exists "eletrica_vistorias_insert" on eletrica_vistorias;
create policy "eletrica_vistorias_insert"
  on eletrica_vistorias for insert
  to authenticated
  with check ((select public.meu_papel()) in ('eletrica','admin'));

drop policy if exists "eletrica_vistorias_update" on eletrica_vistorias;
create policy "eletrica_vistorias_update"
  on eletrica_vistorias for update
  to authenticated
  using ((select public.meu_papel()) in ('eletrica','admin'))
  with check ((select public.meu_papel()) in ('eletrica','admin'));

-- sem policy de DELETE: exclusão é sempre soft-delete via UPDATE (excluido_em)

commit;

-- Verificação pós-migração:
-- select * from eletrica_vistorias order by criado_em desc limit 20;
-- select contratos_edificacao_pode_ler(); -- deve rodar sem erro (não retorna boolean fora de contexto de sessão)
