-- Migração: agendamento de vistorias elétricas (aba "Elétrica", painel lateral
-- "Atenção, Elétrica!" — gecope_mapa_obras.html). Continuação da Fase 1
-- (sql/create_eletrica_vistorias.sql), pedido do usuário em 24/09/2026: a equipe
-- de elétrica quer poder escolher, dentre as obras listadas no painel, quais vão
-- vistoriar e já marcar data + responsável — combinado (grill) que isso fica
-- salvo no banco, visível pra equipe toda, não só nesta sessão do navegador.
--
-- Relação com eletrica_vistorias: tabelas IRMÃS, não uma referenciando a outra.
-- Um agendamento não vira automaticamente o relatório — quando o relatório real é
-- enviado (INSERT em eletrica_vistorias), o agendamento correspondente PERMANECE
-- na tabela (não é apagado nem baixado por trigger nenhum); é o FRONTEND que para
-- de mostrar um agendamento como pendente assim que a obra já tem relatório (ver
-- obrasComAtencaoEletrica() em mapa-obras.js) — mesma decisão de design de deixar
-- a leitura de "pendente/feito" só no app, nunca duplicada em SQL, já usada em
-- toda a Fase 1.
--
-- Sem UNIQUE em id_obra: em tese poderia haver mais de um agendamento ativo pra
-- mesma obra (ex.: reagendar sem cancelar o antigo primeiro) — o app evita isso na
-- UI (não deixa selecionar uma obra que já tem agendamento ativo), mas o banco não
-- impõe. Equipe pequena, mesmo espírito de risco aceito documentado em
-- eletrica_vistorias.
--
-- Uso: rode este arquivo inteiro no SQL Editor do Supabase (Dashboard > SQL Editor).
-- Pré-requisito: sql/create_eletrica_vistorias.sql já aplicado (usa a mesma
-- contratos_edificacao_pode_ler() e o mesmo meu_papel() criados/usados lá).

begin;

-- ── TABELA ──────────────────────────────────────────────────────────────────
create table if not exists eletrica_vistorias_agendadas (
  id                 bigint generated by default as identity primary key,
  id_obra            integer not null,      -- contratos_edificacao.id_obra, sem FK física (mesma convenção de eletrica_vistorias)
  data_planejada     date not null,
  responsavel_nome   text not null,
  criado_por_email   text not null,         -- e-mail do usuário autenticado que agendou
  criado_em          timestamptz not null default now(),
  excluido_em        timestamptz            -- soft delete (NULL = agendamento ativo); nunca DELETE físico
);

create index if not exists idx_eletrica_agenda_obra
  on eletrica_vistorias_agendadas (id_obra) where excluido_em is null;

-- ── RLS ───────────────────────────────────────────────────────────────────
alter table eletrica_vistorias_agendadas enable row level security;

-- leitura: mesmo público de leitura do resto do módulo Contratos (função já criada
-- em sql/create_eletrica_vistorias.sql)
drop policy if exists "eletrica_vistorias_agendadas_select" on eletrica_vistorias_agendadas;
create policy "eletrica_vistorias_agendadas_select"
  on eletrica_vistorias_agendadas for select
  to authenticated
  using ((select public.contratos_edificacao_pode_ler()));

-- insert/update: só eletrica/admin (mesma função public.meu_papel() de eletrica_vistorias).
-- Sem policy de DELETE: cancelamento é sempre soft-delete via UPDATE (excluido_em).
drop policy if exists "eletrica_vistorias_agendadas_insert" on eletrica_vistorias_agendadas;
create policy "eletrica_vistorias_agendadas_insert"
  on eletrica_vistorias_agendadas for insert
  to authenticated
  with check ((select public.meu_papel()) in ('eletrica','admin'));

drop policy if exists "eletrica_vistorias_agendadas_update" on eletrica_vistorias_agendadas;
create policy "eletrica_vistorias_agendadas_update"
  on eletrica_vistorias_agendadas for update
  to authenticated
  using ((select public.meu_papel()) in ('eletrica','admin'))
  with check ((select public.meu_papel()) in ('eletrica','admin'));

commit;

-- Verificação pós-migração:
-- select * from eletrica_vistorias_agendadas order by criado_em desc limit 20;
